"$schema" = 'https://starship.rs/config-schema.json'

format = "$all"
add_newline = false
scan_timeout = 10
command_timeout = 300

[battery]
disabled = true

[cmd_duration]
min_time = 1000
format = '[$duration](bold yellow)'

[directory]
disabled = false
format = '@[$read_only]($read_only_style)[$path]($style) '
home_symbol = '~'
read_only = "â”‡"
repo_root_format = '[$before_root_path]($before_repo_root_style)[$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)'
truncate_to_repo = true
truncation_length = 5
truncation_symbol = '.\'

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
ignore_branches = ["main", "master"]
[git_commit]
tag_symbol = " tag "
[git_status]
disabled = true

[jobs]
number_threshold = 1
format = '[$number$symbol]($style) '
symbol = 'j'

[line_break]
disabled = false

[package]
format = '[$version]($style) '

[shell]
format = 'in [$indicator]($style)'
disabled = true

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

# ----------------------------------

[c]
format = '[$symbol($version(-$name) )]($style)'
[cpp]
format = '[$symbol($version(-$name) )]($style)'
disabled = false
[cmake]
format = '[$symbol($version )]($style)'
[dotnet]
format = '[$symbol($version )(ðŸŽ¯ $tfm )]($style)'
[golang]
format = '[$symbol($version )]($style)'
symbol = 'go '
[nodejs]
format = '[$symbol($version )]($style)'
[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
[typst]
format = '[$symbol($version )]($style)'
