# Config that doesn't interfere with accesibility keys and workspace switching with alt+tab.
general:
  startup_commands: ["shell-exec zebar", "focus --workspace 1"]
  shutdown_commands: ["shell-exec taskkill /IM zebar.exe /F"]
  config_reload_commands: []
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false # don't touch

  cursor_jump:
    enabled: true
    trigger: "monitor_focus"

  hide_method: "cloak"
  show_all_in_taskbar: false

gaps:
  scale_with_dpi: false

  inner_gap: "0px"
  outer_gap:
    top: "0px"
    right: "0px"
    bottom: "0px"
    left: "0px"

window_effects:
  focused_window:
    border:
      enabled: true
      color: "#005000"

    hide_title_bar:
      enabled: false

    corner_style:
      enabled: false
      style: "square"

    transparency:
      enabled: false
      opacity: "99%"

  other_windows:
    border:
      enabled: false
      color: "#400000"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: false
      opacity: "95%"

window_behavior:
  initial_state: "tiling"

  state_defaults:
    floating:
      centered: false
      shown_on_top: false

    fullscreen:
      maximized: false
      shown_on_top: false

#################################################################

workspaces:
  - name: "br0wser"
  - name: "br1wser"
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
  - name: "comms"
  - name: "media"
  - name: "leaveopen1"
    display_name: "lO1"
    cycle_ignore: true
  - name: "leaveopen2"
    display_name: "lO2"
    cycle_ignore: true
  - name: "leaveopen3"
    display_name: "lO3"
    cycle_ignore: true
  - name: "leaveopen4"
    display_name: "lO4"
    cycle_ignore: true
  - name: "game"
  - name: "gamelauncher"
  - name: "dialog"
    cycle_ignore: true

#################################################################

window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { equals: "gInk" }
      - window_process: { equals: "zebar" }

  - commands: ["set-transparency --opacity 0.95", "ignore"]
    match:
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

  - commands: ["move --workspace br0wser"]
    match:
      - window_process: { equals: "Hollama" }
      - window_process: { equals: "librewolf" }

  - commands: ["move --workspace br1wser"]
    match:
      - window_process: { equals: "chrome" }
        window_class: { equals: "Chrome_WidgetWin_1" }

  - commands: ["move --workspace media"]
    match:
      - window_process: { equals: "mpc-hc64" }
      - window_process: { equals: "mpv" }
      - window_process: { equals: "quodlibet" }

  - commands: ["move --workspace comms"]
    match:
      - window_process: { equals: "WhatsApp" }
      - window_process: { equals: "Discord" }
      - window_process: { equals: "vesktop" }
      - window_process: { equals: "Telegram" }
      - window_process: { equals: "thunderbird" }

  - commands: ["move --workspace gamelauncher"]
    match:
      - window_process: { equals: "Heroic" }
      - window_process: { equals: "prismlauncher" }
      - window_process: { equals: "steamwebhelper" }

  - commands: [
        "move --workspace game",
        # "shell-exec --hide-window setresolution.exe -w 1280 -h 720 -o 0 -noprompt -nopersist",
        "set-floating --centered --width 1280 --height 720",
        "set-title-bar-visibility hidden",
        # "set-fullscreen --maximized=true",
      ]
    match:
      - window_process: { equals: "dota2" }

  - commands: ["set-floating --centered --width 1280 --height 720"]
    match:
      - window_title: { equals: "Panorama Debugger" }

  - commands:
      ["move --workspace game", "set-title-bar-visibility hidden", "set-floating --centered --width 1280 --height 720"]
    match:
      - window_process: { equals: "javaw" }
        window_class: { regex: "GLFW30|LWJGL" }

  - commands: ["set-tiling", "size --width 550"]
    match:
      - window_class: { regex: "Minify 1.\\d+\\.?\\d+(rc\\d+)?" }
  #################################################################

  # - commands: ["set-tiling"]
  #   match:

  - commands: ["set-floating --centered"]
    match:
      - window_process: { equals: "devenv" }
      - window_process: { equals: "ProtonVPN" }
      - window_process: { equals: "qView" }

  - commands: ["set-floating --centered --shown-on-top=true"]
    match:
      - window_process: { equals: "mpc-hc64" }

  - commands: ["set-fullscreen --maximized=false", "set-tiling"]
    match:
      - window_process: { equals: "devenv" }
        window_title: { regex: ".* - Microsoft Visual Studio" }

  # contextual dialogs
  - commands: ["set-floating --centered --shown-on-top=true", "set-transparency --opacity 0.75"]
    match:
      - window_process: { equals: "AutoHotkeyUX" }
        window_title: { equals: "Window Spy for AHKv2" }
      - window_process: { equals: "Everything" }
      - window_process: { equals: "explorer" }
        window_class: { equals: "OperationStatusWindow" }
      - window_process: { equals: "DllHost" }
        window_class: { equals: "MediaPlayerClassicW" }
      - window_process: { equals: "notepad++" }
      - window_process: { equals: "notepad" }
      - window_process: { equals: "okular" }
        window_title: { equals: "Go to Page - Okular" }
      - window_process: { equals: "okular" }
        window_title: { equals: "Configure - Okular" }
      - window_process: { equals: "OpenWith" }
      - window_process: { equals: "perfmon" }
      - window_process: { equals: "PickerHost" }
      - window_process: { equals: "prismlauncher" }
        window_title: { regex: "Please wait.*" }
      - window_process: { equals: "qalculate-qt" }
      - window_process: { equals: "Taskmgr" }

  # throw any setup windows & unnecessary dialogs away
  - commands:
      ["move --workspace dialog", "set-floating --centered --shown-on-top=true", "set-transparency --opacity 0.4"]
    match:
      - window_process: { regex: ".*[Ss][Ee][Tt][Uu][Pp].*" }
      - window_class: { regex: ".*[Ss][Ee][Tt][Uu][Pp].*" }
      - window_process: { regex: ".*[Ww][Ii][Zz][Aa][Rr][Dd].*" }
      - window_class: { regex: ".*[Ww][Ii][Zz][Aa][Rr][Dd].*" }
      - window_process: { regex: ".*[Uu][Pp][Dd][Aa][Tt][Ee][Rr].*" }
      - window_class: { regex: ".*[Uu][Pp][Dd][Aa][Tt][Ee][Rr].*" }
      - window_process: { regex: "msiexec" }
      - window_process: { equals: "VSIXInstaller" }
      - window_process: { equals: "steam" }
        window_class: { equals: "BootstrapUpdateUIClass" }
      - window_process: { equals: "v2rayN" }
        window_title: { regex: "v2rayN - .*" }
      - window_process: { equals: "gimp-3" }
        window_title: { equals: "GIMP Startup" }

  - commands:
      [
        "set-floating",
        "set-transparency --opacity 0.75",
        "set-floating --centered --shown-on-top=true --width 385 --height 175",
      ]
    match:
      - window_process: { equals: "pinentry" }

  - commands: ["set-transparency --opacity 0.9"]
    match:
      - window_process: { equals: "explorer" }

  # for windows that resize themselves/don't respect initial states
  - commands: ["wm-redraw"]
    match:
      - window_process: { equals: "javaw" }
      - window_process: { equals: "librewolf" }
        window_class: { equals: "MozillaWindowClass" }
      - window_process: { equals: "soffice" }
        window_class: { regex: "GLFW30|LWJGL" }
      - window_process: { equals: "qView" }

#################################################################

keybindings:
  - commands: ["focus --direction left"]
    bindings: ["alt+shift+a"]
  - commands: ["focus --direction right"]
    bindings: ["alt+shift+d"]
  - commands: ["focus --direction up"]
    bindings: ["alt+shift+w"]
  - commands: ["focus --direction down"]
    bindings: ["alt+shift+s"]

  - commands: ["move --direction left"]
    bindings: ["ctrl+shift+a"]
  - commands: ["move --direction right"]
    bindings: ["ctrl+shift+d"]
  - commands: ["move --direction up"]
    bindings: ["ctrl+shift+w"]
  - commands: ["move --direction down"]
    bindings: ["ctrl+shift+s"]

  - commands: ["resize --width -2%"]
    bindings: ["ctrl+alt+shift+a"]
  - commands: ["resize --width +2%"]
    bindings: ["ctrl+alt+shift+d"]
  - commands: ["resize --height +2%"]
    bindings: ["ctrl+alt+shift+w"]
  - commands: ["resize --height -2%"]
    bindings: ["ctrl+alt+shift+s"]

  - commands: ["wm-toggle-pause"]
    bindings: ["ctrl+alt+shift+p"]

  - commands: ["toggle-tiling-direction"]
    bindings: ['alt+shift+"']

  - commands: ["toggle-floating --centered"]
    bindings: ["ctrl+alt+shift+space"]

  - commands: ["toggle-tiling"]
    bindings: ["alt+shift+q"]

  - commands: ["toggle-fullscreen"]
    bindings: ['ctrl+alt+shift+"']

  - commands: ["wm-reload-config"]
    bindings: ["ctrl+alt+shift+r"]

  - commands: ["focus --next-active-workspace"]
    bindings: ["alt+tab", "f20"]
  - commands: ["focus --prev-active-workspace"]
    bindings: ["alt+shift+tab", "f19"]

  #################################################################

  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]
  - commands: ["focus --workspace br0wser"]
    bindings: ["alt+f1"]
  - commands: ["focus --workspace br1wser"]
    bindings: ["ctrl+alt+f1"]
  - commands: ["focus --workspace comms"]
    bindings: ["alt+f2"]
  - commands: ["focus --workspace media"]
    bindings: ["alt+f3"]
  - commands: ["focus --workspace leaveopen1"]
    bindings: ["alt+f6"]
  - commands: ["focus --workspace leaveopen2"]
    bindings: ["alt+f7"]
  - commands: ["focus --workspace leaveopen3"]
    bindings: ["alt+f8"]
  - commands: ["focus --workspace leaveopen4"]
    bindings: ["alt+f9"]
  - commands: ["focus --workspace game"]
    bindings: ["alt+f10"]
  - commands: ["focus --workspace gamelauncher"]
    bindings: ["alt+f11"]
  - commands: ["focus --workspace dialog"]
    bindings: ["alt+f12"]

  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]
  - commands: ["move --workspace br0wser", "focus --workspace br0wser"]
    bindings: ["alt+shift+f1"]
  - commands: ["move --workspace br1wser", "focus --workspace br1wser"]
    bindings: ["ctrl+alt+shift+f1"]
  - commands: ["move --workspace comms", "focus --workspace comms"]
    bindings: ["alt+shift+f2"]
  - commands: ["move --workspace media", "focus --workspace media"]
    bindings: ["alt+shift+f3"]
  - commands: ["move --workspace leaveopen1", "focus --workspace leaveopen1"]
    bindings: ["alt+shift+f6"]
  - commands: ["move --workspace leaveopen2", "focus --workspace leaveopen2"]
    bindings: ["alt+shift+f7"]
  - commands: ["move --workspace leaveopen3", "focus --workspace leaveopen3"]
    bindings: ["alt+shift+f8"]
  - commands: ["move --workspace leaveopen4", "focus --workspace leaveopen4"]
    bindings: ["alt+shift+f9"]
  - commands: ["move --workspace game", "focus --workspace game"]
    bindings: ["alt+shift+f10"]
  - commands: ["move --workspace game", "focus --workspace gamelauncher"]
    bindings: ["alt+shift+f11"]
  - commands: ["move --workspace dialog", "focus --workspace dialog"]
    bindings: ["alt+shift+f12"]
